# Generated by Django 2.0.5 on 2018-11-29 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_pro', models.BooleanField(default=False)),
                ('subdis_pro', models.BooleanField(default=False)),
                ('uni_pro', models.BooleanField(default=False)),
                ('vil_pro', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, upload_to='profile_image')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('nid', models.IntegerField()),
                ('bith_certification_no', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District')),
            ],
        ),
        migrations.CreateModel(
            name='SubDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District')),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.SubDistrict')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Union')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='subdistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.SubDistrict'),
        ),
        migrations.AddField(
            model_name='profile',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Union'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Village'),
        ),
    ]
