# Generated by Django 2.0.5 on 2018-11-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=False)),
                ('is_editor', models.BooleanField(default=False)),
            ],
        ),
    ]
