# Generated by Django 2.0.5 on 2018-11-30 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_userpermit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_permit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserPermit'),
            preserve_default=False,
        ),
    ]
