# Generated by Django 2.0.5 on 2018-11-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_profile_user_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_permit',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserPermit',
        ),
    ]
