# Generated by Django 2.0.5 on 2018-11-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0006_auto_20181130_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.District'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subdistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.SubDistrict'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='union',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.Union'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userinfo.Village'),
        ),
    ]
